### ISSUE TITLE
Crear conexión con sockets

### ISSUE THREAD

**Issue by ruzafa8** [jdomingu98/ft_irc#1]
Funciones por orden: socket(), bind(), listen(), poll() ==> distinguir entre nuevas conexiones y mensajes que envian clientes que ya existen. (accept())

## Tutorial
https://medium.com/@afatir.ahmedfatir/small-irc-server-ft-irc-42-network-7cee848de6f9

## Imagen de referencia
Se tienen que llamar a las funciones que aparecen aquí.
![Image](https://github.com/jdomingu98/ft_irc/assets/34567477/ecb97c34-e5f8-43e6-9be4-f9173a0d7e67)

## Pruebas
Se puede probar con netcat.

**Comment by jdomingu98** [comment]
Codigo subido en conjunto con la issue #2
