### ISSUE TITLE
[DOC] [ENH] Generación de pruebas en server oficial

### ISSUE THREAD

**Issue by jdomingu98** [jdomingu98/ft_irc#80]
Poned un comentario cada uno con todas las cosas que queráis probar en el servidor real. Cada uno escribirá pruebas sobre lo que ha implementado, y realizaré preguntas si algo no me ha quedado claro.

Realizaré las pruebas y comentaré que cosas se tienen que arreglar/cambiar/mejorar.

**Comment by jdomingu98** [comment]
GENERICO
- Comprobar si se lanza BadChanMaskException
- Comprobar comportamientos con mensajes
- Comprobar mensajes de respuesta y códigos
- Comportamiento ctrl+d

JOIN
- Probar caso de pruebas comentario JoinCommand
- Comprobar que pasa si cuando se envían varios canales y falla uno en medio sigue ejecutándose con los siguientes o para en el fallido (aplicable a otros comandos)

KICK
- Varios canales y varios usuarios, pero diferente longitud

QUIT
- Mensajes del quit cuando ctrl+c o al cerrar manualmente

PART (Nada por ahora)

**Comment by Atrujillo02** [comment]
TOPIC

- Probar mensaje con ":"  y sin el y debatir si se puede modificar el join libsUtils o sino creare una función aparte para que funcione correctamente el Topic.
- Ver como envía el topic a un canal con mas de un cliente
- Probar el Mode #<channel> +t
- Probar un TOPIC sin mensaje
- TOPIC sin estar en un canal
- TOPIC en un canal diferente al tuyo
- Cambiar el Topic a ":"
