### ISSUE TITLE
[AUTH] [BUG] Proceso no se hace correctamente

### ISSUE THREAD

**Issue by jdomingu98** [jdomingu98/ft_irc#82]
Ahora mismo deja poner NICK-USER antes de validar la PASS, lo que genera que aunque despues pongas la PASS correcta debas cambiar el NICK para poder entrar al server.

El comportamiento correcto es primero esperar la PASS y nada más, luego el par NICK (se puede cambiar varias veces antes de poner el user) - USER (solamente 1 vez).
Por último, validar si la contraseña es correcta y, si lo es, dejar entrar al usuario. Si no lo es, no sabra decir si empezar de cero o esperar una nueva PASS hasta que sea correcta.

**Comment by jdomingu98** [comment]
![Image](https://github.com/jdomingu98/ft_irc/assets/97060625/e4678129-1c9c-45ab-8ec6-c378d677ab98)

Los errores de validacion se hacen luego de poner el par NICK-USER

**Comment by ruzafa8** [comment]
![Image](https://github.com/jdomingu98/ft_irc/assets/34567477/0e127a2c-aa48-461e-852d-eb0c6f587dba)

Ergo te echa si pones mal la pass... Me gusta.

**Comment by ruzafa8** [comment]
resuelto por #119
